### ISSUE TITLE
为什么不拓展一步，做一个代理服务器呢？

### ISSUE THREAD

**Issue by Eattttt** [wikiZ/ServerlessScan#1]
感觉这样的话，你目录和端口扫描的功能又要自己写，以后加个新功能又要再写再步，不如直接做一个代理服务器，然后现在存在的工具就能直接使用。我用过SCFPROXY，缺点就是有点不太稳定。

**Comment by wikiZ** [comment]
自己写定制化更高，可以组合多个云函数分工扫描。文章就是提了一下抛砖引玉的作用，毕竟很多师傅需要的场景还是打造自己的扫描器功能。
