### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by epony4c** [wikiZ/ServerlessScan#3]
![image](https://user-images.githubusercontent.com/17228839/148783689-630db424-0ffc-4a3b-866a-65ac28591497.png)

师傅你好。这个问题是咋回事啊？是api配置的问题嘛？

**Comment by wikiZ** [comment]
应该是你python版本过高。

**Comment by wikiZ** [comment]
或者压根没有返回云函数的text，你请求看下api网关地址。可以加微信Z0xy_Root聊
